### ISSUE TITLE
Glitch after version 1.2.4

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/simple_cloud_logging#6]
## Issue

Raising nesting-assertion when nesting is fine.

This is happening when logging inside an `each` loop instead of a `while` loop

```ruby
begin
    l.blank_line
    l.logs "Looking for number 3... "

    numbers = [0, 1, 2, 3, 4, 5]

    numbers.each do |i|
        l.logs "#{i}... " 

        l.logs "Checking... "
        if i == 3
            l.yes 
        else
            l.no 
        end
        i += 1

        l.done
    end

    l.done
rescue => e
    l.error(e)
end
```

```
2024-07-26 18:58:58: Looking for number 3... 
2024-07-26 18:58:58: > 0... error: Log nesting assertion: You missed to close the log-level that you opened at assertion5.rb:49:in `<main>'.
/home/leandro/code/simple_cloud_logging/lib/baselogger.rb:151:in `logs'
/home/leandro/code/simple_cloud_logging/lib/locallogger.rb:46:in `logs'
assertion5.rb:52:in `block in <main>'
assertion5.rb:49:in `each'
assertion5.rb:49:in `<main>'.
```

## Bug Replication

**While Loop:**

```ruby
require_relative '../lib/simple_cloud_logging'

BlackStack::Logger.set(
    nesting_assertion: true,
)

# create a logger
l = BlackStack::LocalLogger.new("assertion.log")

begin
    l.blank_line
    l.logs "Looking for number 3... "

    numbers = [0, 1, 2, 3, 4, 5]

    i = 0
    while i <= 5
        l.logs "#{i}... " 

        l.logs "Checking... "
        if i == 3
            l.yes 
        else
            l.no 
        end
        i += 1

        l.done
    end

    l.done
rescue => e
    l.error(e)
end

=begin
level: 2
level-1: 1
callers: {0=>"assertion5.rb:12:in `<main>'", 1=>"assertion5.rb:18:in `<main>'"}
caller: "assertion5.rb:20:in `<main>'"
=end

**Each Loop:**

begin
    l.blank_line
    l.logs "Looking for number 3... "

    numbers = [0, 1, 2, 3, 4, 5]

    numbers.each do |i|
        l.logs "#{i}... " 

        l.logs "Checking... "
        if i == 3
            l.yes 
        else
            l.no 
        end
        i += 1

        l.done
    end

    l.done
rescue => e
    l.error(e)
end

=begin
level: 2
level-1: 1
callers: {0=>"assertion5.rb:45:in `<main>'", 1=>"assertion5.rb:49:in `<main>'"}
caller: "assertion5.rb:49:in `<main>'"
=end
```

**Comment by leandrosardi** [comment]
Here are the `caller_location` array for each example:

**While Loop:**

```
=> ["/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:77:in `block in repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `loop'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `block in start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:15:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_class.rb:194:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/core_extensions.rb:45:in `pry'",
 "/home/leandro/code/simple_cloud_logging/lib/baselogger.rb:147:in `logs'",
 "/home/leandro/code/simple_cloud_logging/lib/locallogger.rb:46:in `logs'",
 "assertion5.rb:20:in `<main>'"]
```

**Each Loop:**

```
=> ["/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:77:in `block in repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `loop'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `block in start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:15:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_class.rb:194:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/core_extensions.rb:45:in `pry'",
 "/home/leandro/code/simple_cloud_logging/lib/baselogger.rb:147:in `logs'",
 "/home/leandro/code/simple_cloud_logging/lib/locallogger.rb:46:in `logs'",
 "assertion5.rb:52:in `block in <main>'",
 "assertion5.rb:49:in `each'",
 "assertion5.rb:49:in `<main>'"]
```

**Comment by leandrosardi** [comment]
Here is the full script.

```ruby
require_relative '../lib/simple_cloud_logging'

BlackStack::Logger.set(
    nesting_assertion: true,
)

# create a logger
l = BlackStack::LocalLogger.new("assertion.log")

begin
    l.blank_line
    l.logs "Looking for number 3... "

    numbers = [0, 1, 2, 3, 4, 5]

    i = 0
    while i <= 5
        l.logs "#{i}... " 

        l.logs "Checking... "
        if i == 3
            l.yes 
        else
            l.no 
        end
        i += 1

        l.done
    end

    l.done
rescue => e
    l.error(e)
end

=begin
level: 2
level-1: 1
callers: {0=>"assertion5.rb:12:in `<main>'", 1=>"assertion5.rb:18:in `<main>'"}
caller: "assertion5.rb:20:in `<main>'"
=end

begin
    l.blank_line
    l.logs "Looking for number 3... "

    numbers = [0, 1, 2, 3, 4, 5]

    numbers.each do |i|
        l.logs "#{i}... " 

        l.logs "Checking... "
        if i == 3
            l.yes 
        else
            l.no 
        end
        i += 1

        l.done
    end

    l.done
rescue => e
    l.error(e)
end

=begin
level: 2
level-1: 1
callers: {0=>"assertion5.rb:45:in `<main>'", 1=>"assertion5.rb:49:in `<main>'"}
caller: "assertion5.rb:49:in `<main>'"
=end
```

**Comment by leandrosardi** [comment]
Same problem when I call a function and pass the logger as a parameter:

```ruby
require_relative '../lib/simple_cloud_logging'

BlackStack::Logger.set(
    nesting_assertion: true,
)

# create a logger
l = BlackStack::LocalLogger.new("assertion.log")

def check_number(number, logger: nill)
    l = logger || Blackstack::DummyLogger.new(nil)

    l.logs "Checking... "
    if number == 3
        l.yes 
    else
        l.no 
    end
end

begin
    l.blank_line
    l.logs "Looking for number 3... "

    numbers = [0, 1, 2, 3, 4, 5]

    numbers.each do |i|
        l.logs "#{i}... " 

        check_number(i, logger: l)
        i += 1

        l.done
    end

    l.done
rescue => e
    l.error(e)
end
```

```
=> ["/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:77:in `block in repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `loop'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `block in start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:15:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_class.rb:194:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/core_extensions.rb:45:in `pry'",
 "/home/leandro/code/simple_cloud_logging/lib/baselogger.rb:147:in `logs'",
 "/home/leandro/code/simple_cloud_logging/lib/locallogger.rb:46:in `logs'",
 "assertion6.rb:13:in `check_number'",
 "assertion6.rb:30:in `block in <main>'",
 "assertion6.rb:27:in `each'",
 "assertion6.rb:27:in `<main>'"]
```

**Comment by leandrosardi** [comment]
I all cases, the right element is the first one with the after the last element with `locallogger.rb` or `dummylogger.rb`.

**While Loop:**

```
=> ["/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:77:in `block in repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `loop'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `block in start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:15:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_class.rb:194:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/core_extensions.rb:45:in `pry'",
 "/home/leandro/code/simple_cloud_logging/lib/baselogger.rb:147:in `logs'",
 "/home/leandro/code/simple_cloud_logging/lib/locallogger.rb:46:in `logs'",
 "assertion5.rb:20:in `<main>'"] <--------------------------------------------------------------
```

**Each Loop:**

```
=> ["/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:77:in `block in repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `loop'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `block in start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:15:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_class.rb:194:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/core_extensions.rb:45:in `pry'",
 "/home/leandro/code/simple_cloud_logging/lib/baselogger.rb:147:in `logs'",
 "/home/leandro/code/simple_cloud_logging/lib/locallogger.rb:46:in `logs'",
 "assertion5.rb:52:in `block in <main>'", <--------------------------------------------------------------
 "assertion5.rb:49:in `each'",
 "assertion5.rb:49:in `<main>'"]
```
 
**Sub-Function**
 
```
 => ["/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:77:in `block in repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `loop'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `block in start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:15:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_class.rb:194:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/core_extensions.rb:45:in `pry'",
 "/home/leandro/code/simple_cloud_logging/lib/baselogger.rb:147:in `logs'",
 "/home/leandro/code/simple_cloud_logging/lib/locallogger.rb:46:in `logs'",
 "assertion6.rb:13:in `check_number'",  <--------------------------------------------------------------
 "assertion6.rb:30:in `block in <main>'",
 "assertion6.rb:27:in `each'",
 "assertion6.rb:27:in `<main>'"]
```
